const DEFAULT_ITEM_ANIMATION_DURATION = 300;
const TAB_BAR_HEIGHT = 60;
const SIZE_DOT = 60;
const TAB_BAR_COLOR = '#FFFFFF';
const HEIGHT_HOLE = 50;
export {
  DEFAULT_ITEM_ANIMATION_DURATION,
  TAB_BAR_HEIGHT,
  SIZE_DOT,
  TAB_BAR_COLOR,
  HEIGHT_HOLE,
};
