const DEFAULT_ITEM_ANIMATION_DURATION: number = 300;
const TAB_BAR_HEIGHT: number = 60
const SIZE_DOT: number = 60
const TAB_BAR_COLOR: string = '#FFFFFF'
const HEIGHT_HOLE = 50
export {
    DEFAULT_ITEM_ANIMATION_DURATION,
    TAB_BAR_HEIGHT,
    SIZE_DOT,
    TAB_BAR_COLOR,
    HEIGHT_HOLE
};
